"""Add passmark and passed fields to Grade

Revision ID: 949909d47aeb
Revises: 23a17ed26187
Create Date: 2026-02-11 13:03:46.583474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949909d47aeb'
down_revision = '23a17ed26187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
