"""added user settings fields

Revision ID: bb706181c5db
Revises: 949909d47aeb
Create Date: 2026-02-14 23:09:41.023017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb706181c5db'
down_revision = '949909d47aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grading_scale', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passing_mark', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_user_registration', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('default_sort', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('default_sort')
        batch_op.drop_column('allow_user_registration')
        batch_op.drop_column('dark_mode')
        batch_op.drop_column('passing_mark')
        batch_op.drop_column('grading_scale')

    # ### end Alembic commands ###
